version: '3.3'

services:

  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: America/Sao_Paulo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/<user_wsl>/mydocker/data/db:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-test
    restart: always
    ports:
      - 8081:8081
    environment:
      TZ: America/Sao_Paulo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge
